version: '3'
services:
  adminer:
    image: adminer:4.8.0
    network_mode: host
  db:
    image: postgres:13.2
    network_mode: host
    environment:
      POSTGRES_DB: fusionpbx
      POSTGRES_USER: fusionpbx
      POSTGRES_PASSWORD: fusionpbx
  # FusionPBX
  fusionpbx:
    image: <registry>:3c10002-freeswitch-1.10.10-debian-12.1-slim-main
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_USER: fusionpbx
      DB_PASS: fusionpbx
